ads/urls.py
from django.urls import path

from ads.views import AddAdView, AdDeleteView, AdDetailView, AllAdsListView, EditAdView, TagAdListView

app_name = 'ads'

urlpatterns = [
    path('add/', AddAdView.as_view(), name='add_ad'),
    path('edit/<int:pk>/<slug:slug>', EditAdView.as_view(), name='edit_ad'),
    path('delete/<int:pk>/<slug:slug>', AdDeleteView.as_view(), name='delete_ad'),

    path('all/', AllAdsListView.as_view(), name='all_ads_list'),
    path('show_ad/<int:pk>/<slug:slug>', AdDetailView.as_view(), name='ad_detail'),
    path('tag/<slug:slug>/', TagAdListView.as_view(), name='tag_ad_list'),

]

inbox/urls.py
from django.urls import path
from inbox.views import inbox, incoming, send_message, user_search, NewConversation

app_name = "inbox"

urlpatterns = [
    path('', inbox, name="inbox"),
    path("incoming/<username>", incoming, name="incoming"),
    path("send/", send_message, name="send_message"),
    path("new/", user_search, name="usersearch"),
    path("new/<username>", NewConversation, name="newconversation"),
   ]

proietto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from user.views import EditProfileView, ProfileView

urlpatterns = [
    path('admin/admin', admin.site.urls),

    path("user/", include("user.urls")),
    path("inbox/", include("inbox.urls")),
    path("<slug:slug>", ProfileView.as_view(), name='profile'),
    path("<slug:slug>/edit_profile/", EditProfileView.as_view(), name='edit_profile'),

    path('', include('web.urls')),
    path('ads/', include('ads.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user.views import LoginView, logout_view, RegisterView, ChangePassword

app_name = "user"

urlpatterns = [
    path("register", RegisterView.as_view(), name="register"),
    path("login", LoginView.as_view(), name="login"),
    path("logout", logout_view, name="logout"),
    path("change_password", ChangePassword.as_view(), name="change_password"),

]

web/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {#    <link rel="stylesheet" href="{% static 'main.css' %}">#}

    <script src="https://kit.fontawesome.com/f558545230.js" crossorigin="anonymous"></script>

    {% block css %}{% endblock %}

</head>


<body>

{% include 'navbar.html' %}

{#WIADOMOSCI, ALERTY#}
{% include "messages.html" %}


{% block body %}{% endblock %} <br>

{% include 'footer.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

{% block scripts %}{% endblock %}

</body>
</html>

web/templates/footer.html
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/web/style.css' %}">{% endblock %}


<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6>About</h6>
                <p class="text-justify"><i>HELP ME CODE </i> is a place when you can find a mentor to help you learn new
                    skill and solve any issues with your code that you are struggling with
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Categories</h6>
                <ul class="footer-links">
                    <li><a href="{% url 'index' %}">FOOTER ITEM</a></li>
                </ul>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Quick Links</h6>
                <ul class="footer-links">
                    <li><a href="link_about-us">About Us</a></li>
                    <li><a href="lin_contact">Contact Us</a></li>
                    <li><a href="link_privacy_policy">Privacy Policy</a></li>
                    <li><a href="link-terms-and-conditions">Terms and Conditions</a></li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text">Copyright HELP ME CODE 2020
                </p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <ul class="social-icons">
                    <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

web/templates/index.html
{% extends "base.html" %}

{% block title %} HOME PAGE / INDEX {% endblock %}


{% block body %}

    <div class="container">
        THIS IS HOMEPAGE CONTENT / INDEX
    </div>

{% endblock %}

web/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == "error" %} danger {% else %}{{ message.tags }}
{% endif %}">

            {% autoescape off %}
                {{ message }}
            {% endautoescape %}

        </div>
    {% endfor %}
{% endif %}

web/templates/navbar.html
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/web/style.css' %}">{% endblock %}


{% if user.is_authenticated %}

    HELLO <a href="{% url 'profile' user.username %}">{{ user.username }} </a>
    <a href="{% url 'inbox:inbox' %}">INBOX</a>
    <a href="{% url "edit_profile" user.slug %}">EDIT PROFILE</a>
    <a href="{% url "user:change_password" %}">CHANGE PASSWORD</a>
    <a href="{% url "user:logout" %}">LOGOUT</a><br>
    <a href="{% url 'index' %}">HOME</a><br>
    <a href="{% url 'ads:add_ad' %}"> ADD AD </a>
    <a href="{% url 'ads:all_ads_list' %}">ALL ADS </a> <br>


{% else %}

    <a href="{% url "user:login" %}">LOGIN</a>
    <a href="{% url "user:logout" %}">LOGOUT</a>
    <a href="{% url "user:register" %}">REGISTER</a><br>

    <a href="{% url 'index' %}">HOME</a><br>
    <a href="{% url 'ads:all_ads_list' %}">ALL ADS </a> <br>
{% endif %}