ads/urls.py
from django.urls import path

from ads.views import AddAdView, AdDeleteView, AdDetailView, AllAdsListView, EditAdView, TagAdListView

app_name = 'ads'

urlpatterns = [
    path('add/', AddAdView.as_view(), name='add_ad'),
    path('edit/<int:pk>/<slug:slug>', EditAdView.as_view(), name='edit_ad'),
    path('delete/<int:pk>/<slug:slug>', AdDeleteView.as_view(), name='delete_ad'),

    path('all/', AllAdsListView.as_view(), name='all_ads_list'),
    path('show_ad/<int:pk>/<slug:slug>', AdDetailView.as_view(), name='ad_detail'),
    path('tag/<slug:slug>/', TagAdListView.as_view(), name='tag_ad_list'),

]

proietto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from user.views import EditProfileView, ProfileView

urlpatterns = [
    path('admin/admin', admin.site.urls),

    path("user/", include("user.urls")),
    path("inbox/", include("inbox.urls")),
    path("<slug:slug>", ProfileView.as_view(), name='profile'),
    path("<slug:slug>/edit_profile/", EditProfileView.as_view(), name='edit_profile'),

    path('', include('web.urls')),
    path('ads/', include('ads.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from hitcount.models import HitCountMixin
from hitcount.settings import MODEL_HITCOUNT
from taggit.managers import TaggableManager
from tinymce.models import HTMLField


class Created(models.Model):
    created_on = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        abstract = True


class Ad(Created, HitCountMixin):
    title = models.CharField(max_length=120)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True, upload_to='ad_images/')
    short_description = models.TextField(null=False, blank=False, max_length=300)
    long_description = HTMLField(blank=False, null=False, max_length=1500)
    tags = TaggableManager()
    slug = models.SlugField(null=False, unique=False)

    hit_count_generic = GenericRelation(
        MODEL_HITCOUNT, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('ads:ad_detail', kwargs={'pk': self.pk, 'slug': self.slug})

    def ad_tags(self):
        return ", \n".join([x.name for x in self.tags.all()])

ads/forms/adeditform.py
from django import forms

from tinymce.widgets import TinyMCE

from ads.models import Ad



class EditAdForm(forms.ModelForm):
    title = forms.CharField(
        label="Title",
        max_length=120,
        help_text="Max 120 characters",
        widget=forms.TextInput(attrs={"class": "form-control form-control-lg pr-5 shadow p-1 mb-1 bg-white rounded"}),
        required=True,
    )

    image = forms.ImageField(
        label="Photo",
        help_text="We accept jpg, png, etc.",
        widget=forms.ClearableFileInput(
            attrs={"class": "form-control form-control pr-3 shadow p-1 mb-1 bg-white rounded"}), required=True,
    )

    short_description = forms.CharField(
        label="Short description",
        max_length=300,
        help_text="Add short description of your problem.",
        widget=forms.Textarea(attrs={"class": "form-control form-control-lg pr-5 shadow p-1 mb-1 bg-white rounded"}),
        required=True,

    )

    long_description = forms.CharField(
        label="Long description",
        max_length=1500,
        help_text="Give us more details about your problem",
        widget=TinyMCE(attrs={}),
        required=True,
    )

    class Meta:
        model = Ad
        fields = ('title', 'image',  'short_description', 'long_description')

ads/forms/adform.py
from django import forms
from taggit.forms import TagWidget
from tinymce.widgets import TinyMCE

from ads.models import Ad


class AdForm(forms.ModelForm):
    title = forms.CharField(
        label="Title",
        max_length=120,
        help_text="Max 120 characters",
        widget=forms.TextInput(attrs={"class": "form-control form-control-lg pr-5 shadow p-1 mb-1 bg-white rounded"}),
        required=True,
    )

    image = forms.ImageField(
        label="Photo",
        help_text="We accept jpg, png, etc.",
        widget=forms.ClearableFileInput(
            attrs={"class": "form-control form-control pr-3 shadow p-1 mb-1 bg-white rounded"}), required=False,
    )

    short_description = forms.CharField(
        label="Short description",
        max_length=300,
        help_text="Add short description of your problem.",
        widget=forms.Textarea(attrs={"class": "form-control form-control-lg pr-5 shadow p-1 mb-1 bg-white rounded"}),
        required=True,

    )

    long_description = forms.CharField(
        label="Long description",
        max_length=1500,
        help_text="Give us more details about your problem",
        widget=TinyMCE(attrs={}),
        required=True,
    )

    class Meta:
        model = Ad
        fields = ('title', 'image', 'tags', 'short_description', 'long_description')
        widgets = {
            'tags': TagWidget(attrs={"class": "form-control form-control-lg pr-5 shadow p-1 mb-1 bg-white rounded"}),
        }

ads/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin as BaseLoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from hitcount.views import HitCountDetailView

from ads.forms.adform import AdForm
from ads.models import Ad


class LoginRequiredMixin(BaseLoginRequiredMixin):
    def get_login_url(self):
        messages.warning(request=self.request, message="You must login first.")
        return reverse("user:login")


class AddAdView(LoginRequiredMixin, CreateView):
    model = Ad
    template_name = 'ads/add_ad.html'
    form_class = AdForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(request=self.request, message='Your ad has been added.')
        return super().form_valid(form)


class EditAdView(LoginRequiredMixin, UpdateView):
    template_name = 'ads/ad_edit.html'
    form_class = AdForm
    model = Ad

    def get_success_url(self):
        pk = self.kwargs["pk"]
        slug = self.kwargs['slug']
        messages.success(request=self.request, message="Edit success!")
        return reverse_lazy("ads:ad_detail", kwargs={'pk': pk, 'slug': slug})


class AdDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Ad
    template_name = 'ads/ad_delete.html'

    def test_func(self):
        ad = self.get_object()
        if self.request.user == ad.author:
            return True
        return False

    def get_success_url(self):
        messages.success(request=self.request, message="You successfuly deleted ad!")
        return reverse_lazy('ads:all_ads_list')


class AllAdsListView(ListView):
    template_name = 'ads/ads_list.html'
    model = Ad
    paginate_by = 5

    def get_queryset(self):
        return self.model.objects.all().order_by('-pk')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['common_tags'] = Ad.tags.most_common()[:10]
        return context


class AdDetailView(HitCountDetailView):
    template_name = 'ads/ad_detail.html'
    model = Ad
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['similar_ads'] = self.object.tags.similar_objects()[:5]
        return context

    def get_success_url(self):
        pk = self.kwargs["pk"]
        slug = self.kwargs['slug']
        return reverse_lazy('ads:article_detail', kwargs={'pk': pk, 'slug': slug})


class TagAdListView(ListView):
    template_name = 'ads/tag_ad_list.html'
    model = Ad
    queryset = Ad.objects.order_by('-pk')
    paginate_by = 5

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(
            tags__slug=self.kwargs['slug'])

    def ad_tag(self):
        return get_object_or_404(Ad.tags, slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['common_tags'] = Ad.tags.most_common()[:10]
        return context

ads/templates/ads/ad_delete.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/ads/style.css' %}">{% endblock %}

{% block title %} DELETE {{ ad.title | upper }} {% endblock %}


{% block body %}

    <div class="page_title"> DELETE: {{ ad.title | upper }} </div>

    <div class="container">

        <form method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            Do you want delete: {{ object.title }} <br>
            ARE YOU SURE? <br>
            <button type="submit" class="btn btn-outline-danger">DELETE</button>
            <a class="btn btn-outline-secondary" href="{% url 'ads:ad_detail' pk=ad.pk slug=ad.slug %}">CANCEL </a>
        </form>
    </div>
{% endblock %}

ads/templates/ads/ad_detail.html
{% extends "base.html" %}
{% load hitcount_tags %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/ads/style.css' %}">
{% endblock %}

{% block title %} DETAILS: {{ ad.title | upper }}  {% endblock %}

{% block body %}

    <div class="page_title">DETAILS OF: {{ ad.title | upper }}</div>

    <div class="container">
        {% if ad.image %}
            <img class="ad_detail_image" src="{{ ad.image.url }}" alt="Photo">
        {% else %}
            THERE IS NO IMAGE :(((
        {% endif %}
        <br>

        {{ ad.title | upper }} <br>

        {% for tag in ad.tags.all %}
            <a href="{% url 'ads:tag_ad_list' tag.slug %}"
               class="badge badge-secondary">{{ tag | lower }}</a>
        {% endfor %} <br>

        {% if user.id == ad.author.id %}
            <small>
                <a class="btn btn-outline-primary btn-sm" role="button"
                   href="{% url 'ads:edit_ad' pk=ad.pk slug=ad.slug %}"><i
                        class="far fa-edit"></i> edit</a>
                <a class="btn btn-outline-primary btn-sm" role="button"
                   href="{% url 'ads:delete_ad' pk=ad.pk slug=ad.slug %}"><i
                        class="far fa-trash-alt"></i> delete</a> <br>
            </small>
        {% endif %}

        Date: {{ ad.created_on.date }} <br>
        Time: {{ ad.created_on.time }} <br>

        Views (total): {{ hitcount.total_hits }} <br>
        Views (last 10 mins): {% get_hit_count for ad within "minutes=10" %} <br>
        {{ ad.long_description | safe }}


        <a href="{% url 'profile' ad.author %}">
            {% if ad.author.photo %}
                <img class="profile_photo"
                     src="{{ ad.author.photo.url }}" alt="Photo">
            {% else %}
                <img class="profile_photo"
                     src="{% static 'images/default_photo.png' %}" alt="Photo">
            {% endif %}
        </a>
        <br>

        Autor: <a href="{% url 'profile' ad.author %}"> {{ ad.author }} </a> <br>
        {% if ad.author.website_url %}
            <a class="btn btn-outline-primary btn-sm" role="button"
               href="{{ ad.author.website_url }}"> <i class="fas fa-house-user"></i> </a>
        {% endif %}
        {% if ad.author.facebook_url %}
            <a class="btn btn-outline-primary  btn-sm" role="button"
               href="{{ ad.author.facebook_url }}"> <i class="fab fa-facebook"></i> </a> <br>
        {% endif %}
        <br>

        SIMILAR ADS (by tags): <br>
        {% for ad in similar_ads %}
            <a href="{{ ad.get_absolute_url }}"> {{ ad.title }} </a> <br>
        {% endfor %}


    </div>
{% endblock %}

ads/templates/ads/ad_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/ads/style.css' %}">{% endblock %}

{% block title %} BEATSPOT: ZAKTUALIZUJ {{ article.title }} {% endblock %}


{% block body %}

    <div class="page_title">EDIT: {{ ad.title }} </div>

    <div class="container">

        {% if user.id == ad.author.id %}
            <div class="form">
            <form method="post" enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form.media }}
                {{ form.title|as_crispy_field }}
                {{ form.image|as_crispy_field }}
                {{ form.tags|as_crispy_field }}


                {{ form.short_description|as_crispy_field }}
                {{ form.long_description|as_crispy_field }}
                <p class="btnwrap">
                    <button type="submit" class="btn btn-outline-primary">SAVE CHANGES</button>
                </p>


            </form>

        {% else %}
            YOU CANNOT EDIT THIS AD GAGATKU!!!
        {% endif %}
        </div>
    </div>
{% endblock %}

ads/templates/ads/add_ad.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/ads/style.css' %}">{% endblock %}

{% block title %}ADS AD{% endblock %}

{% block body %}
    <div class="page_title"> ADD AD</div>


    <div class="container">
        <div class="form">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form.media }}

                {{ form.title|as_crispy_field }}
                {{ form.image|as_crispy_field }}
                {{ form.tags |as_crispy_field }}
                {{ form.short_description|as_crispy_field }}
                {{ form.long_description|as_crispy_field }}

                <p class="btnwrap">
                    <button type="submit" class="btn btn-outline-primary">ADD AD</button>
                </p>
            </form>

        </div>
    </div>


{% endblock %}

ads/templates/ads/ads_list.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/ads/style.css' %}">{% endblock %}

{% block title %} ALL ADS {% endblock %}

{% block body %}

    <div class="page_title"> ALL Ads</div>

    {% include 'ads/ads_list_base.html' %}

    {% include 'ads/pagination_base.html' %}

{% endblock %}

ads/templates/ads/ads_list_base.html
<div class="container">


    {% if object_list %}

        MOST COMMON TAGS:
        {% for tag in common_tags %}
            <a href="{% url 'ads:tag_ad_list' tag.slug %}"
               class="badge badge-secondary">{{ tag | lower }}</a>
        {% endfor %} <br> <br>


        {% for ad in object_list %}

            <h3><a href="{{ ad.get_absolute_url }}"> {{ ad.title|upper }} </a></h3>

            {% for tag in ad.tags.all %}
                <a href="{% url 'ads:tag_ad_list' tag.slug %}"
                   class="badge badge-secondary">{{ tag | lower }}</a>
            {% endfor %} <br>

            {{ ad.author }} <br>
            {{ ad.created_on }} <br>
            {{ ad.short_description }} <br><br>

        {% endfor %}

    {% else %}
        Nothing to see here :(((((
    {% endif %}
</div>

ads/templates/ads/pagination_base.html
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/ads/style.css' %}">{% endblock %}

<div class="pagination">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&laquo; PREV </a>
        {% endif %}
        &nbsp; SITE NR {{ page_obj.number }} FROM {{ page_obj.paginator.num_pages }}. &nbsp;
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"> NEXT &raquo;</a>
        {% endif %}
    {% endif %}
</div>

ads/templates/ads/tag_ad_list.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/ads/style.css' %}">{% endblock %}

{% block title %} ALL TAG {{ view.ad_tag.name|upper }} ADS {% endblock %}



{% block body %}

    <div class="page_title"> ALL TAG {{ view.ad_tag.name|upper }} ADS</div>

    {% include 'ads/ads_list_base.html' %}

    {% include 'ads/pagination_base.html' %}

{% endblock %}